project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!projects"
  resources:
    - projects/dsan-5000/_site
    - projects/Abortion Policy and Health Wellness Outcomes by State/website/_site
    - projects/gun-violence/website/_site
    - projects/scholarship/website/_site
    - certifications-awards   # Add this line
    - images

website:
  title: "Portfolio"
  favicon: "images/gu-logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: undergrad/competition.qmd       # Add this line
        text: Competitions

      - text: "Undergraduate Research"
        menu: 
        - text: "Swimming with Deep Learning"
          href: undergrad/REU.qmd
        - text: "Crime and Mobility Analytics"
          href: undergrad/REU.qmd        # Add this line

      - text: "Georgetown Projects"
        menu: 
          - text: DSAN-5000
            href: projects/dsan-5000/_site/index.html
          - text: "Abortion Policy Analysis"
            href: projects/Abortion Policy and Health Wellness Outcomes by State/website/_site/index.html
          - text: "Gun Violence"
            href: projects/gun-violence/website/_site/index.html
          - text: "Humanitarian Aid"
            href: projects/scholarship/website/_site/index.html
          - text: DSAN-5200
            href: projects/hiv/website/_site/index.html
          - text: DSAN-5400
            href: projects/dsan-5400/website/docs/index.html

format:
  html:
    css: styles.css
    toc: true



