project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!projects"
  resources:
    - projects/dsan-5000/_site
    - projects/Abortion Policy and Health Wellness Outcomes by State/website/_site
    - certifications-awards   # Add this line
    - images

website:
  title: "Portfolio"
  favicon: "images/gu-logo.png"
  navbar:
    left:
      - href: undergrad/competition.qmd       # Add this line
        text: Competitions
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu: 
          - text: DSAN-5000
            href: projects/dsan-5000/_site/index.html
          - text: "Abortion Policy Analysis"
            href: projects/Abortion Policy and Health Wellness Outcomes by State/website/_site/index.html

format:
  html:
    css: styles.css
    toc: true



